apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    name: orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      name: orders
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: punithaj07/orders
          imagePullPolicy: IfNotPresent
      restartPolicy: Always