apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    name: payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      name: payments
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: punithaj07/payments
          imagePullPolicy: IfNotPresent
      restartPolicy: Always