apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingcart
  labels:
    name: shoppingcart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoppingcart
  template:
    metadata:
      name: shoppingcart
      labels:
        app: shoppingcart
    spec:
      containers:
        - name: shoppingcart
          image: punithaj07/shoppingcart
          imagePullPolicy: IfNotPresent
      restartPolicy: Always