apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    name: products
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      name: products
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: punithaj07/products
          imagePullPolicy: IfNotPresent
      restartPolicy: Always